import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@splitflow/css-reset'
import './globals.css'
import { SplitflowAppProvider, SsrRegistryProvider } from './_lib/contexts'
import { createSplitflowAppKit, loadSplitflowAppBundle } from '@splitflow/app'
import '@splitflow/css-reset/index.css'
import { appConfig } from './_lib/configs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const app = createSplitflowAppKit(appConfig)
    const bundle = await loadSplitflowAppBundle(app)

    return (
        <html lang="en">
            <body className={'sf-css-reset ' + inter.className}>
                <SsrRegistryProvider>
                    <SplitflowAppProvider bundle={bundle}>{children}</SplitflowAppProvider>
                </SsrRegistryProvider>
            </body>
        </html>
    )
}
